<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="LAPTOP-SJQUN0GA" failures="0" tests="1" name="Default test" time="1.038" errors="0" timestamp="2023-04-22T00:50:07 IST">
  <testcase classname="com.base.AutomationBase" name="@BeforeTest prelaunch" time="0.502">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;java.io.FileInputStream.close()&amp;quot; because &amp;quot;fis&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.io.FileInputStream.close()" because "fis" is null
at com.utils.PropertyUtils.getProperty(PropertyUtils.java:36)
at com.base.AutomationBase.prelaunch(AutomationBase.java:34)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:644)
at org.testng.TestRunner.beforeRun(TestRunner.java:633)
at org.testng.TestRunner.run(TestRunner.java:595)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest prelaunch -->
  <testcase classname="com.test.ExpensePageTest" name="@BeforeMethod prerun" time="0.0">
    <skipped/>
  </testcase> <!-- @BeforeMethod prerun -->
  <testcase classname="com.test.ExpensePageTest" name="validateTheElementInAddExpensePopup" time="0.001">
    <skipped/>
  </testcase> <!-- validateTheElementInAddExpensePopup -->
  <testcase classname="com.test.ExpensePageTest" name="validateEnteredValueInAddExpensePopUpIsSaved" time="0.0">
    <ignored/>
  </testcase> <!-- validateEnteredValueInAddExpensePopUpIsSaved -->
  <testcase classname="com.test.ExpensePageTest" name="validatenAddExpensePopUpfields" time="0.0">
    <ignored/>
  </testcase> <!-- validatenAddExpensePopUpfields -->
  <testcase classname="com.test.ExpensePageTest" name="modifyTheExistingRecordOfExpense" time="0.0">
    <ignored/>
  </testcase> <!-- modifyTheExistingRecordOfExpense -->
  <testcase classname="com.test.ExpensePageTest" name="validateDeleteFunctiongOfExistingRecord" time="0.0">
    <ignored/>
  </testcase> <!-- validateDeleteFunctiongOfExistingRecord -->
</testsuite> <!-- Default test -->
